### ISSUE TITLE
怎么修改播放器的视频地址

### ISSUE THREAD

**Issue by leoFitz1024** [wangrongding/tiny-player#10]
就是先初始化好播放器，然后别的事件触发修改视频地址

我使用src属性修改视频地址不行
![image](https://github.com/wangrongding/tiny-player/assets/29174699/06be75af-47e9-4420-9185-b7998690c7f0)

**Comment by wangrongding** [comment]
@leoFitz1024  可以了吗？

**Comment by leoFitz1024** [comment]
> @leoFitz1024 可以了吗？

这个问题解决了，但是还碰到一个问题，我这边是想在单html文件中使用，然后直接浏览器打开文件能够播放视频，mp4文件没问题，但是m3u8文件依赖hls.js，引入了这个js还是存在问题，只能转向使用video.js了
