### ISSUE TITLE
键盘控制

### ISSUE THREAD

**Issue by wswmsword** [wangrongding/tiny-player#3]
作者可以加上视频播放器的键盘控制，比如焦点在滑块的时候，方向键控制进度，焦点在音量的时候，左右方向键调节音量。

**Comment by wangrongding** [comment]
> 作者可以加上视频播放器的键盘控制，比如焦点在滑块的时候，方向键控制进度，焦点在音量的时候，左右方向键调节音量。

感谢建议，后续将添加上
